#!/bin/bash

# read inputs

list=$1

dos2unix $list

for filename in `cat $list`; do

flirt -in skull_stripped_1mm/${filename}_PETBrainExtractionBrain..nii -ref /Users/mattiacannistra/fsl/data/standard/MNI152_T1_1mm_brain -out flirt_1mm/${filename}_PET.nii.gz -omat flirt_1mm/${filename}_PET.mat -bins 256 -cost corratio -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 12  -interp trilinear

done

